export const GET_KITTIES_REQUEST = 'GET_KITTIES_REQUEST'
export const GET_KITTIES_SUCCESS = 'GET_KITTIES_SUCCESS'
export const GET_KITTIES_ERROR = 'GET_KITTIES_ERROR'
export const SELECT_KITTY = 'SELECT_KITTY'